### ISSUE TITLE
Provide packages for Ubuntu 22.04

### ISSUE THREAD

**Issue by ssesik** [Snapchat/KeyDB#432]
Currently KeyDB doesn't provide packages for Ubuntu 22.04 (jammy) and it would be nice if packages for jammy can be provided.

**Comment by dup2** [comment]
Would be nice!

**Comment by HDVinnie** [comment]
Anything?

**Comment by Serpent6877** [comment]
Adding to the request for Jammy support.

**Comment by syedrizwansrs** [comment]
Would be nice to have it on 22.04!

**Comment by benschermel** [comment]
This support is planned to be included in our next point release and onwards. We are targeting a point release prior to EOY

**Comment by dup2** [comment]
Any progress on this? It is a real blocker for a lot of users..

**Comment by cklm** [comment]
For everyone who wants to build KeyDB self on Ubuntu 22 - use the following commands (as root):

    apt update
    apt install autogen autoconf libtool libssl-dev build-essential nasm autotools-dev libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev git
    git clone https://github.com/EQ-Alpha/KeyDB.git
    cd KeyDB
    make
    make install

Find `keydb-server` and `keydb-cli` in KeyDB/src/ afterwards.

**Comment by shleeable** [comment]
I'm looking to deploy on Jammy/ubuntu 22.04. Please consider this

**Comment by Eskies** [comment]
> For everyone who wants to build KeyDB self on Ubuntu 22 - use the following commands (as root):
> 
> ```
> apt update
> apt install autogen autoconf libtool libssl-dev build-essential nasm autotools-dev libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev git
> git clone https://github.com/EQ-Alpha/KeyDB.git
> cd KeyDB
> make
> make install
> ```
> 
> Find `keydb-server` and `keydb-cli` in KeyDB/src/ afterwards.


I got an error while trying to build on Ubuntu 22.04 
```
    CC server.o
In file included from server.h:89,
                 from server.cpp:31:
server.cpp: In function ‘int clientsCronTrackExpansiveClients(client*, int)’:
zmalloc.h:58:25: error: ‘je_malloc_usable_size’ was not declared in this scope; did you mean ‘malloc_usable_size’?
   58 | #define zmalloc_size(p) je_malloc_usable_size(p)
      |                         ^~~~~~~~~~~~~~~~~~~~~
server.cpp:1911:34: note: in expansion of macro ‘zmalloc_size’
 1911 |                       (c->argv ? zmalloc_size(c->argv) : 0);
      |                                  ^~~~~~~~~~~~
server.cpp: In function ‘int clientsCronTrackClientsMemUsage(client*)’:
zmalloc.h:58:25: error: ‘je_malloc_usable_size’ was not declared in this scope; did you mean ‘malloc_usable_size’?
   58 | #define zmalloc_size(p) je_malloc_usable_size(p)
      |                         ^~~~~~~~~~~~~~~~~~~~~
server.cpp:1931:12: note: in expansion of macro ‘zmalloc_size’
 1931 |     mem += zmalloc_size(c);
      |            ^~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-atomic-alignment’ may have been intended to silence earlier diagnostics
make[1]: *** [Makefile:482: server.o] Error 1
make[1]: Leaving directory '/home/ubuntu/KeyDB/src'
make: *** [Makefile:6: all] Error 2
```

Please help.

**Comment by benschermel** [comment]
Thanks everyone for your patience on this ;)

Packages are now provided for Ubuntu 22.04 (Jammy) as of v6.3.2 and can be downloaded via our PPA following these instructions: [https://docs.keydb.dev/docs/ppa-deb](https://docs.keydb.dev/docs/ppa-deb)

@Eskies regarding your build inquiry, try using all deps as described in README: `sudo apt install build-essential nasm autotools-dev autoconf libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev libbz2-dev libzstd-dev liblz4-dev libsnappy-dev libssl-dev`. If you still have an issue building please open a new issue. Closing this issue as Jammy packages are now provided.

**Comment by padinko** [comment]
is possible to get version of 6.2 for ubuntu jammy?
because of this bug https://github.com/Snapchat/KeyDB/issues/453 it is impossible to use on production 6.3 version
